a = int(input("Enter the 1st number: "))
# b = int(input("Enter the 2nd number: "))
# c = int(input("Enter the 3rd number: "))
# d = int(input("Enter the 4th number: "))
# e = int(input("Enter the 5th number: "))
# f = int(input("Enter the 6th number: "))
# g = int(input("Enter the 7th number: "))
# h = int(input("Enter the 8th number: "))
# s = {a,b,c,d,e,f,g,h}
# print(type(s))
# print(s)